server:
  port: 8888

spring:
  redis:
    host: 192.168.0.111
    port: 6379
  activemq:
    broker-url: tcp://192.168.0.111:61616 # mq服务器地址
    user: admin
    password: admin
  jms:
    pub-sub-domain: false  # fale = 队列，true = 主题

#自定义队列名称
myqueue: boot-activemq-queue